# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    # Location of the manifest files
    directories:
      - "/src/**"
    # Optionally, you can specify a schedule for when Dependabot checks for updates.
    schedule:
      interval: "monthly"
    # Raise all NuGet pull requests with assignees
    assignees:
      - "caveman8080"
    labels:
      - "nuget dependencies"